### ISSUE TITLE
GHES support

### ISSUE THREAD

**Issue by emilva** [praetorian-inc/gato#11]
Hello, this looks like an awesome tool!

Is it possible to add a cli flag for github api url? That would enable support for GitHub Enterprise Server :)

Cheers,

emil

**Comment by mas0nd** [comment]
Hello, thanks for checking it out!

We can most definitely add an experimental flag for supporting GHES. Our only concern, and the reason for not including it in the first place, is that we haven't had the opportunity to test Gato against an Enterprise instance. With some potential differences in the GHES API and the Github.com API, we would greatly appreciate any feedback/pr's addressing issues/gaps identified. I'll work on adding that shortly and reference here. 

Thanks!

**Comment by emilva** [comment]
Cool!

I can happily test it against our instance :)

There is usually some lag with regards to new features landing in GHES, but all old and stable features should co-exists in the GHES API too.

I am not very savvy with Python, but I would deffo help out with PR if I were :) 

Thanks,

emil

**Comment by mas0nd** [comment]
@emilva 
Please give #12 a shot and let us know if you run into any issues. Thank you so much!

**Comment by mas0nd** [comment]
Hello @emilva!

Have you been able to give this a shot against your GHES instance? Any feedback would be greatly appreciated!

**Comment by emilva** [comment]
@mas0nd hey and sorry for the late response, was at a conference last week.

I will give this a go today.

Thanks,

emil

**Comment by AdnaneKhan** [comment]
The feature is now in the development branch, closing this issue.
