### ISSUE TITLE
Verbose Error Logs 

### ISSUE THREAD

**Issue by jimmyscchang** [praetorian-inc/gato#16]
If the user does not have proper permissions to clone the GitHub repository, verbose error logs are generated when attempting to run the enumerate command 

![gato](https://user-images.githubusercontent.com/10868567/218172141-e90b423b-033a-49bb-b390-493d302db50f.png)

**Comment by AdnaneKhan** [comment]
Thanks for the bug report! To make sure I understand the behavior correctly:

Are you running this with a token that does not have clone privileges?

OR

Are you running this with an appropriately scoped token, but that user does not have read access to the repository?

**Comment by mas0nd** [comment]
Actually, in this case, the user was unable to clone the repository due to SSH cert authentication requirements.
![image](https://user-images.githubusercontent.com/31484153/218213930-fe951949-35ec-47ad-ab9b-cf9b4bc13ac6.png)

**Comment by mas0nd** [comment]
@AdnaneKhan It looks like the source of these messages is that we set the root logging level to DEBUG.

We have this in a few places, but we might want to rethink how we are using the logging package.

https://github.com/praetorian-inc/gato/blob/b347c55a9142944b4d9cd362ed01daeebb3938ab/gato/enumerate/enumerate.py#L19

**Comment by AdnaneKhan** [comment]
DEBUG root level is no longer set.
