### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by di1l0o** [praetorian-inc/gato#41]
What happened?

![image](https://github.com/praetorian-inc/gato/assets/58363074/ee9ef6b7-c1e9-467e-b136-cb64a97372be)

**Comment by AdnaneKhan** [comment]
What environment are you seeing this error in? The following would be helpful:

* Type of OS
* Are you running in a container
* Python3 Version

**Comment by di1l0o** [comment]
I run it in a container.

I use docker to run it.

ubuntu20.04

python3.8

**Comment by AdnaneKhan** [comment]
I tried to replicate this with the following on a fresh docker container but did not see the error:

Start docker container:

```
docker run -ti ubuntu:focal /bin/bash
```

Install dependencies and Gato:

```
apt update
apt install git
apt install python3 python3.8-venv
git clone https://github.com/praetorian-inc/gato
cd gato
python3 -m venv venv
source venv/bin/activate
pip install .
gato
```

Could you try running through these steps and let me know if you see different behavior?

**Comment by di1l0o** [comment]
![image](https://github.com/praetorian-inc/gato/assets/58363074/1b0dfec6-bcec-4377-9ddd-61bf30dbca63)

**Comment by di1l0o** [comment]
However, I get this problem

![image](https://github.com/praetorian-inc/gato/assets/58363074/3f7ab108-7777-47f3-a307-92b6b7c368bb)

**Comment by AdnaneKhan** [comment]
> However, I get this problem
> 
> ![image](https://user-images.githubusercontent.com/58363074/260409311-3f7ab108-7777-47f3-a307-92b6b7c368bb.png)

Very strange, and you followed the exact instructions as above? I'm curious about what your docker host OS is. I ran that on OS X,  so perhaps there is something unusual going on when running it on a Linux docker host.

**Comment by AdnaneKhan** [comment]
closing this for now as i have not been able to replicate it.
